--- 

 - name: install required packages
   apt:
           name: "{{ item }}"
           update_cache: true
           state: present
   with_items:
           - 'build-essential' 
           - 'python-dev' 
           - 'python-virtualenv'
           - 'libcurl4-nss-dev'
           - 'libcurl3' 
           - 'libsasl2-dev' 
           - 'libsasl2-modules' 
           - 'maven'
           - 'libapr1-dev' 
           - 'libsvn-dev' 
           - 'zlib1g-dev'
           - 'libevent-dev'
           - 'autoconf'
           - 'libtool'
 - name: add key for mesos installation
   shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E56151BF

 - name: update the system
   apt:
           update_cache: yes
   
 - name: add the repository to source.list.d
   shell: 'echo "deb http://repos.mesosphere.io/ubuntu `lsb_release -cs` main"| sudo tee /etc/apt/sources.list.d/mesosphere.list'

 - name: update the system
   apt:
           update_cache: yes

 - name: install mesos and marathon
   apt:
           name: "{{ item }}"
   with_items:
           - 'mesos=1.0.1*'
           - 'marathon=1.1.3*'
 - debug:
        msg: "{{ groups['zoo1'] }}"

 - debug:
        msg: "{{ inventory_hostname }}"

 - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']

 - name: configure zk in mesos
   template:
           src: zk
           dest: /etc/mesos/zk

 - name: configure zoo
   template:
           src: zoo.cfg
           dest: /etc/zookeeper/conf/zoo.cfg
 
 - name: configure hostname for mesos-master
   template:
           src: hostname
           dest: /etc/mesos-master/hostname 

 - name: configure quorum for mesos-master
   template:
           src: quorum
           dest: /etc/mesos-master/quorum

 - name: configure quorum
   when: inventory_hostname == 'mesos1'
   template:
           src: myid1
           dest: /etc/zookeeper/conf/myid

 - name: configure quorum
   when: inventory_hostname == 'mesos2'
   template:
           src: myid2
           dest: /etc/zookeeper/conf/myid

 - name: configure quorum
   when: inventory_hostname == 'mesos3'
   template:
           src: myid3
           dest: /etc/zookeeper/conf/myid

 - name: create folder for marathon
   file:
           path: /etc/marathon/conf
           state: directory
           mode: '0777'

 - name: configure marathon_conf hostname
   template:
           src: hostname
           dest: /etc/marathon/conf/hostname

 - name: configure marathon_conf zk as marathon
   template:
           src: zk_marathon
           dest: /etc/marathon/conf/zk

 - name: configure marathon_conf zk as master
   template:
           src: zk
           dest: /etc/marathon/conf/master

 - name: start maually to override 
   command: 'echo manual | sudo tee /etc/init/mesos-slave.override'

 - name: update the system
   apt:
           update_cache: yes


 - name: restart zookeeper  
   service:
           name: zookeeper
           state: restarted

 - name: restart mesos-master
   service:
           name: mesos-master
           state: restarted

 - name: restart marathon  
   service:
           name: marathon
           state: restarted
